### PR TITLE
Fix incorrect type variance being applied on generated adapters 

### LINKED ISSUE #1009: Generated adapters redeclare type variable variance
Carrying over from https://github.com/square/moshi/issues/1008#issuecomment-550513501. These should just be a no-variant typevariable

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #1009. Also fixes a discovered boxed types bug along the way and refactors the type mapping to a new `mapTypes` API for reuse.

### CODE REVIEW

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt [hunk 1]
```diff
@@ -95,3 +99,48 @@ internal fun KModifier.checkIsVisibility() {
...
+        else -> throw UnsupportedOperationException("Not possible.")
+      }
+    }
+    else -> throw UnsupportedOperationException("Type '${javaClass.simpleName}' is illegal. Only classes, parameterized types, wildcard types, or type variables are allowed.")
+  }
+}
+
+internal fun TypeName.stripTypeVarVariance(): TypeName {
+  return mapTypes<TypeVariableName> {
+    TypeVariableName(name = name, bounds = bounds.map { it.mapTypes(TypeVariableName::stripTypeVarVariance) }, variance = null)
```
Comment (swankjesse) [inline kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt]: style nit: we wrap at 100 columns in Moshi style
