### PR TITLE
Refuse kotlin classes in ClassJsonAdapter

### LINKED ISSUE #748: Require reflection or codegen for Kotlin types
When you don’t have either installed things sort of work, but there are traps. It would be better to fail early with an obvious explanation of what’s wrong.

https://github.com/square/moshi/issues/743

### PR DESCRIPTION
**Pull request by hzsweers**
Resolves #748

There are two existing tests that fail with this now, let me know what you all want to do with them (migrate/adjust/delete/etc)

`KotlinJsonAdapterTest#delegatesToInstalledAdaptersBeforeNullChecking`

`KotlinJsonAdapterTest#nullablePrimitivesUseBoxedPrimitiveAdapters`

### CODE REVIEW

**Comment by NightlyNexus** [comment]
Simply my mistakes in those tests. will need a rebase after #750

File: kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt [hunk 1]
```diff
@@ -950,4 +950,16 @@ class KotlinJsonAdapterTest {
     assertThat(adapter.fromJson("null")).isNull()
     assertThat(adapter.toJson(null)).isEqualTo("null")
   }
+
+  @Test fun kotlinClassesWithoutAdapterAreRefused() {
+    val moshi = Moshi.Builder().build()
+    try {
+      moshi.adapter<PlainKotlinClass>(PlainKotlinClass::class.java)
+      throw AssertionError("Should not pass here")
```
Comment (NightlyNexus) [inline kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt]: nit: use `fail()`? for consistency with all the other test cases.

File: moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java [hunk 2]
```diff
@@ -75,6 +75,14 @@
       if (Modifier.isAbstract(rawType.getModifiers())) {
         throw new IllegalArgumentException("Cannot serialize abstract class " + rawType.getName());
       }
+      for (Annotation annotation : rawType.getDeclaredAnnotations()) {
+        if ("kotlin.Metadata".equals(annotation.annotationType().getName())) {
+          throw new IllegalArgumentException("Cannot serialize Kotlin type " + rawType.getName()
+              + ". Reflective serialization of Kotlin classes without using kotlin-reflect can "
+              + "have undefined and unexpected behavior. Please use KotlinJsonAdapter from the "
```
Comment (NightlyNexus) [inline moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java]: nit: instead of "can have undefined and unexpected behavior," how about "has undefined and unexpected behavior?"

File: kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt (hunk 1 above)
Comment (hzsweers) [reply kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt]: derp, good call 7058846

File: moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java (hunk 2 above)
Comment (hzsweers) [reply moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java]: Done ca79cce

**Comment by hzsweers** [comment]
Rebased!

File: moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java [hunk 3]
```diff
@@ -75,6 +75,14 @@
       if (Modifier.isAbstract(rawType.getModifiers())) {
         throw new IllegalArgumentException("Cannot serialize abstract class " + rawType.getName());
       }
+      for (Annotation annotation : rawType.getDeclaredAnnotations()) {
```
Comment (swankjesse) [inline moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java]: This is a very expensive reflection call. Calling isAnnotationPresent is much faster. Can you change to that?

Comment (swankjesse) [reply moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java]: You might need to load the metadata class using Class.forName() and that can fail. If it does, I don't _think_ it's possible for Kotlin to be present.

Comment (hzsweers) [reply moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java]: > Calling isAnnotationPresent is much faster. Can you change to that?

Can do, completely forgot about that. #754

> I don't think it's possible for Kotlin to be present

Kotlin technically could be present, but only if the stdlib isn't used. We wouldn't be able to tell in this case :/
