### PR TITLE
Fix a crash when processing a parameter annotated with an annotation that placed in annotation package

### LINKED ISSUE #1203: Moshi's generated adapaters do not support Explicit API mode
Kotlin 1.4 added [Explicit API Mode](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) which applies stricter rules to promote more stable public APIs. 

These rules also apply to generated code, and currently (tested with version 1.10.0), Moshi does not generate visibility modifiers on generated adapter classes, which causes warnings or errors (depending on configuration).

### PR DESCRIPTION
**Pull request by kubode**
This problem happens with KotlinPoet 1.7.x.

From KotlinPoet 1.7.x, `TypeName.toString()` is escaped with backquotes if the package name contains keywords.

e.g. `ClassNames.get(java.lang.annotation.Annotation::class).toString()`

KotlinPoet 1.6.x | KotlinPoet 1.7.x
--|--
`java.lang.annotation.Annotation` | ``java.lang.`annotation`.Annotation``

So NPE will be thrown if an annotation is placed in `annotation` package because `elements.getTypeElement(it.typeName.toString())` returns `null`.

Edit: Also resolves #1203

### CODE REVIEW

**Review by ZacSweers — COMMENTED** [review]
Good catch but this is sort of the wrong solution because it also doesn't work right? We should be grabbing the canonical classname

**Comment by kubode** [comment]
Ah, you are right.
Do you know of any code that can replace `TypeName.toString()` on KotlinPoet 1.7.x?
I'm not familiar with KotlinPoet, so if you know, please let me know.

**Comment by kubode** [comment]
Seems like `TypeName.toString()` can replace with `TypeName.rawType().canonicalName`.

**Comment by ZacSweers** [comment]
Yep I think that's the right replacement to use

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt [hunk 1]
```diff
@@ -483,7 +483,7 @@ internal fun TargetProperty.generator(
 private fun List<AnnotationSpec>?.qualifiers(elements: Elements): Set<AnnotationSpec> {
   if (this == null) return setOf()
   return filterTo(mutableSetOf()) {
-    elements.getTypeElement(it.typeName.toString()).getAnnotation(JSON_QUALIFIER) != null
+    elements.getTypeElement(it.typeName.rawType().canonicalName)?.getAnnotation(JSON_QUALIFIER) != null
```
Comment (ZacSweers) [inline kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt:486]: We should not have a null classname here so let's fail eagerly like before

File: kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt [hunk 2]
```diff
@@ -468,6 +468,28 @@ class JsonClassCodegenProcessorTest {
     assertThat(result.messages).contains("JsonQualifier @UpperCase must have RUNTIME retention")
   }
 
+  @Test
+  fun `Processor should not fail with a qualifier that placed in 'annotation' package`() {
```
Comment (ZacSweers) [inline kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt:472]: This test doesn't actually test the original issue. Please move this to the generated adapters tests/ subproject and make a full test that also then tries to load the generated adapter

Comment (kubode) [reply kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt:472]: Do you mean that I should move this test case to `GeneratedAdaptersTest`?

After upgrading KotlinPoet to 1.7.x, I have a problem that `GeneratedAdaptersTest_MultiplePropertiesShareAdapterJsonAdapter` is not generated on my local and the test fails.

image


<details><summary>KotlinPoet 1.7.2 Gradle log</summary>

```
> Task :kotlin:tests:compileTestKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
21 actionable tasks: 4 executed, 17 up-to-date
e: /Users/masatoshi/Git/moshi/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt: (988, 28): Unresolved reference: GeneratedAdaptersTest_MultiplePropertiesShareAdapterJsonAdapter
e: /Users/masatoshi/Git/moshi/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt: (990, 9): Unresolved reference: it
e: /Users/masatoshi/Git/moshi/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt: (992, 5): Overload resolution ambiguity: 
public open fun assertThat(p0: Optional<*>?): GuavaOptionalSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Multimap<*, *>?): MultimapSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Multiset<*>?): MultisetSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Table<*, *, *>?): TableSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Class<*>?): ClassSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: BigDecimal?): BigDecimalSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Any?): Subject! defined in com.google.common.truth.Truth
public open fun <T : Any!> assertThat(p0: Array<(out) TypeVariable(T)!>?): ObjectArraySubject<TypeVariable(T)!>! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Boolean?): BooleanSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: BooleanArray?): PrimitiveBooleanArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: ByteArray?): PrimitiveByteArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: CharArray?): PrimitiveCharArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Double?): DoubleSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: DoubleArray?): PrimitiveDoubleArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Float?): FloatSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: FloatArray?): PrimitiveFloatArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Int?): IntegerSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: IntArray?): PrimitiveIntArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Long?): LongSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: LongArray?): PrimitiveLongArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: ShortArray?): PrimitiveShortArraySubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: String?): StringSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: Throwable?): ThrowableSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: (Mutable)Iterable<*>?): IterableSubject! defined in com.google.common.truth.Truth
public open fun assertThat(p0: (Mutable)Map<*, *>?): MapSubject! defined in com.google.common.truth.Truth
e: /Users/masatoshi/Git/moshi/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt: (1352, 7): Unresolved reference: GeneratedAdaptersTest_MultipleGenericsJsonAdapter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlin:tests:compileTestKotlin'.
> Compilation error. See log for more details

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kotlin:tests:compileTestKotlin'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$$Lambda$597/000000000000000000.accept(Unknown Source)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$$Lambda$528/000000000000000000.execute(Unknown Source)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:14)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:127)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:152)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:147)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompilerAsync(GradleKotlinCompilerRunner.kt:73)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:432)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:357)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(Tasks.kt:318)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:570)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:555)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:538)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:279)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:268)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep$$Lambda$677/000000000000000000.apply(Unknown Source)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at org.gradle.internal.execution.steps.SkipUpToDateStep$$Lambda$593/000000000000000000.apply(Unknown Source)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep$$Lambda$566/000000000000000000.get(Unknown Source)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:195)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$$Lambda$528/000000000000000000.execute(Unknown Source)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```
</details>


However, CI is successful.

I do not know the cause. Please let me know if you have any suggestions.

Comment (alexvanyo) [reply kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt:472]: Just a heads up here, CI was likely successful due to #1294

Comment (kubode) [reply kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt]: I moved this test case to `GeneratedAdaptersTest`, and all tests passed on my local.

image

Comment (kubode) [reply kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt]: 8bff67e
Seems like the build was failing with `shadowJar` due to `com.google.guava` added to `kotlinpoet-classinspector-elements` dependencies from 1.7.x.

File: kotlin/codegen/build.gradle.kts [hunk 3]
```diff
@@ -65,9 +65,11 @@ dependencies {
     exclude(group = "org.jetbrains.kotlin")
     exclude(group = "com.squareup", module = "kotlinpoet")
   }
+  api(Dependencies.KotlinPoet.elementsClassInspector)
   shade(Dependencies.KotlinPoet.elementsClassInspector) {
     exclude(group = "org.jetbrains.kotlin")
     exclude(group = "com.squareup", module = "kotlinpoet")
+    exclude(group = "com.google.guava")
```
Comment (ZacSweers) [inline kotlin/codegen/build.gradle.kts:72]: what were these for?

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt [hunk 4]
```diff
@@ -483,7 +483,10 @@ internal fun TargetProperty.generator(
 private fun List<AnnotationSpec>?.qualifiers(elements: Elements): Set<AnnotationSpec> {
   if (this == null) return setOf()
   return filterTo(mutableSetOf()) {
-    elements.getTypeElement(it.typeName.toString()).getAnnotation(JSON_QUALIFIER) != null
+    val typeElement = requireNotNull(elements.getTypeElement(it.typeName.rawType().canonicalName)) {
```
Comment (ZacSweers) [inline kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt:486]: `checkNotNull` is more appropriate here as this is not an argument

```suggestion
    val typeElement = checkNotNull(elements.getTypeElement(it.typeName.rawType().canonicalName)) {
```

File: kotlin/codegen/build.gradle.kts (hunk 3 above)
Comment (kubode) [reply kotlin/codegen/build.gradle.kts:72]: I don't understand `shadowJar` well, but it seems that `guava` has been added to the dependencies of `kotlinpoet-classinspector-elements` from 1.7.x, which broke the jar file of the output of the `shadowJar` task and caused `kapt` to fail.
Therefore, `guava` was excluded to make the build successful.

**Comment by kubode** [comment]
@ZacSweers Can you please review this again?

File: kotlin/codegen/build.gradle.kts (hunk 3 above)
Comment (ZacSweers) [reply kotlin/codegen/build.gradle.kts:72]: That makes me uncomfortable as kotlinpoet uses guava APIs then, removing it likely breaks the artifact. Can you be more specific about what issues you encountered?

Comment (kubode) [reply kotlin/codegen/build.gradle.kts:72]: Before I excluded `guava` (cdc51e9), the `:kotlin:tests:compileTestKotlin` task had `Unresolved reference: GeneratedAdaptersTest_MultipleProperti esShareAdapterJsonAdapter` error.
In this case, the `:kotlin:tests:kaptTestKotlin` task did not give an error and I could not find a solution.

Next I thought there might be a problem with `shadowJar`.

Here are the contents of the `jar` file that is the artifact of the `:kotlin:codegen:shadowJar` task before I excluded `guava` (cdc51e9).

KotlinPoet 1.6 | KotlinPoet 1.7
-- | --
image | image

When I saw this, I thought that `guava` might have broken `shadowJar`, so I excluded `guava` from the `shade` dependency. Then `./gradlew build` got successful.

I don't know why moshi using `shadowJar`, should I write the `rerocate` configuration for `guava` in `shadowJar` block?

Comment (ZacSweers) [reply kotlin/codegen/build.gradle.kts:72]: Thanks for the detailed writeup. In this case, I think it's ok because we're telling it just to exclude guava from shading but not from the actual API

**Review by ZacSweers — APPROVED** [review]

**Comment by ZacSweers** [comment]
Thanks!
