### PR TITLE
Let JsonValueReader.nextString read numbers.

### LINKED ISSUE #388: JsonValueReader.nextString() does not coerce numbers to strings.
```java 
@Test public void numberToStringCoersion() throws Exception {
  JsonReader reader = newReader("[0, 9223372036854775807, 1.5]");
  reader.beginArray();
  assertThat(reader.nextString()).isEqualTo("0");
  assertThat(reader.nextString()).isEqualTo("9223372036854775807");
  assertThat(reader.nextString()).isEqualTo("1.5");
  reader.endArray();
}
```

This test passes with a JsonUtf8Reader and fails (`com.squareup.moshi.JsonDataException: Expected STRING but was 0.0, a java.lang.Double, at path $[0]`) with a JsonValueReader.

### PR DESCRIPTION
**Pull request by NightlyNexus**
This adds parity with JsonUtf8Reader and lets big number literals in JSON be read in as strings in Java.

PR note:
```java
Moshi moshi = new Moshi.Builder().build();
JsonAdapter<String> adapter = moshi.adapter(String.class);
JsonReader reader = JsonReader.of(new Buffer().writeUtf8("9223372036854775808"));
String bigMoney = adapter.fromJsonValue(reader.readJsonValue());
```
This change will make the above work (instead of throwing, expecting a double), so that you can use big numbers in polymorphic adapters where you need to read in the map.

Closes #388.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Looking on my computer now I guess it's hard to do both because of the difference in initialization.

**Comment by JakeWharton** [comment]
Looking on my computer now I guess it's hard to do both because of the difference in initialization.

**Comment by NightlyNexus** [comment]
Yeah, but the differences make a good point:
Since JsonValueReader is only exposed via `readJsonValue()`, doubles are the only numbers.
I don't think this approach really helps users.

**Comment by NightlyNexus** [comment]
Er, via JsonAdapter.fromJsonValue, but I don't know how many people are using that without JsonReader.readJsonValue(). (though i might be biased in my use cases.)

**Comment by NightlyNexus** [comment]
there's probably no use in getting strings, since you'll have lose precision in a value reader (like in my PR comment example), no matter what you do.

**Comment by NightlyNexus** [comment]
Sorry for the delay here.
Also, sorry, I conflated too many things here.
The context is that I'd like to blog about polymorphic deserialization and unusual JSON formats.
</br>
</br>
I would like this code
```java
// "Buffered" code.
Moshi moshi = new Moshi.Builder().build();
JsonAdapter<Object> objectAdapter = moshi.adapter(Object.class);
JsonAdapter<String> numberAdapter = moshi.adapter(String.class);
String number = numberAdapter.fromJsonValue(objectAdapter.fromJson("17"));
```
to result the same as this code
```java
// "Streaming" code.
Moshi moshi = new Moshi.Builder().build();
JsonAdapter<String> numberAdapter = moshi.adapter(String.class);
String number = numberAdapter.fromJson("17");
```

This PR does that. (The code isn't quite right but could be fixed.)
</br>
</br>
There's a twist. This might be out of the scope of discussion here.

There cannot be analogous "buffered" code for the "streaming" code below because we prefer doubles for number types. (Gson had its own `LazilyParsedNumber`.) Moshi requires registering a custom adapter to get the same behavior across the "streaming" code and "buffered" code.
```
// "Streaming" code.
Moshi moshi = new Moshi.Builder().build();
JsonAdapter<String> stringAdapter = moshi.adapter(String.class);
String number = stringAdapter.fromJson("9223372036854775808");
```
</br>
</br>

2 options I see:
- Close this issue. Leave the first and second example code above broken. Recommend using a custom adapter.
- Patch to make the first code example work. Recommend using a custom adapter if expecting big numbers.

File: moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java [hunk 1]
```diff
@@ -423,6 +424,18 @@
     }
   }
 
+  @Test public void numberToStringCoersion() throws Exception {
+    JsonReader reader = new JsonValueReader(Arrays.asList(0, 9223372036854775807L, 2.5d, 3.010f, "a", "5"));
```
Comment (swankjesse) [inline moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java]: is there any reason to have the trailing `0` in `3.010f` ?

**Comment by swankjesse** [comment]
I like this as-is.

As a general rule, I don’t want to encourage people to put numeric values into JSON that can’t be represented as a `double`. That is asking for trouble.

File: moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java (hunk 1 above)
Comment (NightlyNexus) [reply moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java]: nope, it's copy-paste from the other test case. will remove.

File: moshi/src/main/java/com/squareup/moshi/JsonValueReader.java [hunk 2]
```diff
@@ -152,9 +152,19 @@
...
-    remove();
-    return peeked;
+    Object peeked = (stackSize != 0 ? stack[stackSize - 1] : null);
+    if (peeked instanceof String) {
+      remove();
+      return (String) peeked;
+    }
+    if (peeked instanceof Number) {
+      remove();
+      return peeked.toString();
```
Comment (NightlyNexus) [inline moshi/src/main/java/com/squareup/moshi/JsonValueReader.java]: this should probably be `BigDecimal(peeked).toPlainString()`.

**Comment by NightlyNexus** [comment]
>As a general rule, I don’t want to encourage people to put numeric values into JSON that can’t be represented as a double. That is asking for trouble.

Thanks, I'm going to note this when writing about this. 👍

File: moshi/src/main/java/com/squareup/moshi/JsonValueReader.java (hunk 2 above)
Comment (NightlyNexus) [reply moshi/src/main/java/com/squareup/moshi/JsonValueReader.java]: no, dunno what i was thinking.

File: moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java [hunk 3]
```diff
@@ -336,6 +336,18 @@ private void assertNotANumber(String s) throws IOException {
     assertEquals("-0", reader.nextString());
   }
 
+  @Test public void numberToStringCoersion() throws Exception {
+    JsonReader reader = newReader("[0, 9223372036854775807, 2.5, 3.010, \"a\", \"5\"]");
+    reader.beginArray();
+    assertThat(reader.nextString()).isEqualTo("0");
+    assertThat(reader.nextString()).isEqualTo("9223372036854775807");
+    assertThat(reader.nextString()).isEqualTo("2.5");
+    assertThat(reader.nextString()).isEqualTo("3.010");
```
Comment (swankjesse) [inline moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java]: The retained precision here is interesting!
