### PR TITLE
Fix support for classes w/ multiple constructors in code gen

### LINKED ISSUE #975: kotlin codgen: multiple constructors with default lead to crash
```kotlin
@JsonClass(generateAdapter = true)
class Foo(val f: Int)

@JsonClass(generateAdapter = true)
class Bar(val f: Foo = Foo(5), val b: Int) {
	constructor(f: Int, b: Int = 6): this(Foo(f), b)
}
@ExperimentalStdlibApi
fun main() {
	val moshi = Moshi.Builder().build()
	moshi.adapter<Bar>().fromJson("""{"b":6}""")
}
```
fails with
```
Exception in thread "main" java.lang.IllegalArgumentException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at moshiTest.BarJsonAdapter.fromJson(BarJsonAdapter.kt:55)
	at moshiTest.BarJsonAdapter.fromJson(BarJsonAdapter.kt:17)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:43)
	at moshiTest.MainKt.main(main.kt:46)
	at moshiTest.MainKt.main(main.kt)
```
The problem is that kotlin generates multiple methods with the `DefaultConstructorMarker` argument. That leads to a chance of the `fromJson` code choosing the wrong constructor in `Util.lookupDefaultsConstructor`.

### PR DESCRIPTION
**Pull request by ZacSweers**
This fixes #975 by directly looking up the constructor via `getDeclaredConstructors` and the exact parameter types + mask and default constructor marker.

### CODE REVIEW

**Comment by ZacSweers** [comment]
Considered other options but felt this was best

Pros:
- Proguard-safe
- No more runtime `Util` requirement, all code is directly in code gen
Cons:
- A bit dense in generated code

Other options considered:

- Look up constructor by jvm method signature
  - Extremely not proguard safe, checks every possible constructor via string comparison
- Add `@MoshiConstructor` annotation to designate which constructor should be used
  - Could make proguard rules easier, but unclear if this annotation is actually copied to the defaults constructor
  - Still requires iterating all constructors searching for it
  - Error prone - what happens if someone mistakenly applies it to multiple constructors?
  - Requires users to make code changes to work, when the regression right now was that it worked without configuration before.

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt [hunk 1]
```diff
@@ -98,6 +109,25 @@ internal class AdapterGenerator(
       .initializer("null")
       .build()
 
+//  private val getOrFindConstructorRefFunction = FunSpec.builder(
```
Comment (swankjesse) [inline kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt]: remove

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt [hunk 2]
```diff
@@ -49,10 +53,41 @@ internal fun TypeName.defaultPrimitiveValue(): CodeBlock =
...
-      UNIT, Void::class.asTypeName() -> throw IllegalStateException("Parameter with void or Unit type is illegal")
+      UNIT, Void::class.asTypeName(), NOTHING -> throw IllegalStateException("Parameter with void, Unit, or Nothing type is illegal")
       else -> CodeBlock.of("null")
     }
 
+internal fun TypeName.asTypeBlock(): CodeBlock {
+  when (this) {
+    is ParameterizedTypeName -> {
+      return if (rawType == ARRAY) {
+        CodeBlock.of("%T::class.java", copy(nullable = false))
```
Comment (swankjesse) [inline kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt]: does this do the right thing? `List<String>::class.java` ?

Comment (ZacSweers) [reply kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt]: This is only for arrays, which are special. For other generic types it just takes the raw type.

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt (hunk 1 above)
Comment (ZacSweers) [reply kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt]: x

Comment (ZacSweers) [reply kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt]: 7e53156

File: kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt (hunk 2 above)
Comment (ZacSweers) [reply kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt]: Resolving this since I think it was just a misunderstanding and want to build the multi-mask support on top of this, can revisit if you think the array handling is still problematic!
